class_name BoxTypes
enum BoxType {WINNER, EMPTY, LOSS, REVEAL_RANDOM, REVEAL_ROW, ONE_GOLD, POISON, ANTIDOTE, EXPLODING, PAY_FOR_REVEALS, STAR, SHADOW, JUMPSCARE, SAFETY, TWO_GOLD, FIRE, THREE_GOLD, SPEND_TO_WIN, REVEAL_CORNERS, DRAGON, SWORD,
GHOST, CLOCK, BOOKS, SACRIFICE, POVERTY, CLOSE_ADJACENT, THREE_D, 
INCOME, BOSS, SHY, MIMIC, CURSE, PAY_FOR_SHIELD, HEART, MUSIC, 
SUS, SPEEDRUN, DEMOLITION, HEARTBREAK, ROWBOMB, CLOSENEXT, AUTOOPEN, ROWWIN, TEACHER, 
ARMAGEDDON, BEDROCK, CLOAK, DESERT, FAIRY, HAT, INVERT, SELFDESTRUCT, WAND, INSTAOPEN, 
BLACKJACK, EGG, INFERNO, KEY, LOCK, MATCH, PANDORAS, REVIVAL, SMARTBOMB, TERRITORY, WORLDBEARER, 
PRINCESS, MINE, CLONE, GAMER, MAGNIFYING, VIRUS, STARVE, SPIRE, CRUMBLING, TRIPLEPLAY, FOOD, ALLSEEINGEYE, 
WATERFALL, METEOR, DAREDEVIL, PAINT, ICE, BULLSEYE, CONFIDENTIAL, FISHING_ROD, IMPATIENT, TRANSMOG, STUCK, FISH, DNA, 
GUARDIAN, PAINTTWO, MOON, BUTTERFLY, MAP, TREASURE, CHECKBOX, STELLAR, FLYING, UNDERWORLD, PROGRAM, SLEEPY, EXP, IVY,
MAX}
